version: '3.8'

services:
  bachhoasi-worker:
    container_name: bachhoasi-worker-management
    image: ${DOCKER_USERNAME}/bach-hoa-si-worker:latest
    restart: always
    environment:
      DB_URL: postgresql-bachhoasi
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      BUCKET: ${BUCKET}
      GG_CREDENTIAL_PATH: /bachhoasi/key
      GG_CREDENTIAL_NAME: ${GG_CREDENTIAL_NAME}
    volumes:
      - ${GG_LOCAL_CREDENTIAL_PATH}:/bachhoasi/key
    networks:
      - bachhoasi-networks

networks:
  bachhoasi-networks:
    name: bachhoasi-networks
    external: true

