version: '3.8'
services:
  bachhoasi-cache:
    container_name: bachhoasi-cache-redis
    image: redis:alpine
    networks:
      - bachhoasi-networks
      
  bachhoasi-worker:
    container_name: bachhoasi-worker-management
    image: ${DOCKER_USERNAME}/bach-hoa-si-worker:latest
    restart: always
    environment:
      DB_URL: postgresql-bachhoasi
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      BUCKET: ${BUCKET}
      GG_CREDENTIAL_NAME: ${GG_CREDENTIAL_NAME}
      GG_CREDENTIAL_JSON: ${GG_CREDENTIAL_JSON}
      REDIS_URL: bachhoasi-cache
      REDIS_PORT: 6379
    networks:
      - bachhoasi-networks

networks:
  bachhoasi-networks:
    name: bachhoasi-networks
    external: true

