spring:
    application:
      name: bachhoasi-worker
    datasource:
        url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
        naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    sql:
        init:
            mode: always
            
    servlet:
        multipart: 
            max-file-size: 10MB
            max-request-size: 10MB
    profiles:
        active: production
        
google:
    credentials:
        json: ${GG_CREDENTIAL_JSON:}
        config-name: ${GG_CREDENTIAL_NAME:bachhoasi.json}
    firebase:
        bucket: ${BUCKET}

bot:
    username: ${BOT_USERNAME:bot}
    password: ${BOT_PASS:bot12345}

redis:
    url: ${REDIS_URL}
    port: ${REDIS_PORT}